import { resolve } from 'node:path';
import { scoreTools, DEFAULT_CONTEXT_WINDOW } from '../score/score.js';
import { resolveServerSource } from '../sources/resolve.js';
import type { LeaderboardRow, Tokenizer } from '../types.js';
import type { LoadedEntry } from './load.js';

export type LeaderboardOptions = {
  tokenizer: Tokenizer;
  contextWindow?: number;
  /** Per-server timeout for launching and querying a live server. */
  timeoutMs?: number;
  /** How many servers to score concurrently. */
  concurrency?: number;
  /** Called after each row settles, for progress output. */
  onProgress?: (row: LeaderboardRow, done: number, total: number) => void;
  /** Root used to resolve `file` sources. Defaults to the process cwd. */
  cwd?: string;
};

/**
 * Score every registry entry.
 *
 * A server that cannot be reached is never a hard failure: it becomes a
 * `pending` row carrying the reason. That is deliberate, because most entries
 * need a network fetch and some need credentials, and a leaderboard that refuses
 * to render when one server is down is useless in CI.
 */
export async function buildLeaderboard(
  entries: LoadedEntry[],
  options: LeaderboardOptions,
): Promise<LeaderboardRow[]> {
  const concurrency = Math.max(1, options.concurrency ?? 4);
  const rows: LeaderboardRow[] = new Array(entries.length);
  let cursor = 0;
  let done = 0;

  const worker = async (): Promise<void> => {
    for (;;) {
      const index = cursor;
      cursor += 1;
      if (index >= entries.length) {
        return;
      }
      const loaded = entries[index];
      if (!loaded) {
        return;
      }
      const row = await scoreEntry(loaded, options);
      rows[index] = row;
      done += 1;
      options.onProgress?.(row, done, entries.length);
    }
  };

  await Promise.all(Array.from({ length: Math.min(concurrency, entries.length) }, worker));
  return rows.filter((r): r is LeaderboardRow => Boolean(r));
}

async function scoreEntry(loaded: LoadedEntry, options: LeaderboardOptions): Promise<LeaderboardRow> {
  const { slug, entry } = loaded;
  const source =
    entry.source.type === 'file'
      ? { ...entry.source, path: resolve(options.cwd ?? process.cwd(), entry.source.path) }
      : entry.source;

  try {
    const tools = await resolveServerSource(source, { timeoutMs: options.timeoutMs });
    const score = scoreTools(tools, options.tokenizer, {
      source: slug,
      contextWindow: options.contextWindow ?? DEFAULT_CONTEXT_WINDOW,
    });
    return { slug, entry, status: 'scored', score };
  } catch (error) {
    return {
      slug,
      entry,
      status: 'pending',
      reason: error instanceof Error ? error.message : String(error),
    };
  }
}

/** Sort scored rows cheapest first, with pending rows last. */
export function rankRows(rows: LeaderboardRow[]): LeaderboardRow[] {
  return [...rows].sort((a, b) => {
    if (a.status !== b.status) {
      return a.status === 'scored' ? -1 : 1;
    }
    if (a.status === 'scored' && b.status === 'scored') {
      return (a.score?.totalTokens ?? 0) - (b.score?.totalTokens ?? 0);
    }
    return a.slug.localeCompare(b.slug);
  });
}

/** Render `LEADERBOARD.md`. */
export function renderLeaderboardMarkdown(rows: LeaderboardRow[], tokenizer: Tokenizer): string {
  const ranked = rankRows(rows);
  const scored = ranked.filter((r) => r.status === 'scored');
  const pending = ranked.filter((r) => r.status === 'pending');

  const lines: string[] = [];
  lines.push('# MCP tool-schema leaderboard');
  lines.push('');
  lines.push(
    'Generated by `tooltax leaderboard --write`. Do not edit by hand -- CI regenerates this file.',
  );
  lines.push('');
  lines.push(
    `Tokenizer: \`${tokenizer.id}\` (${tokenizer.label}). ` +
      `Context share assumes a ${formatNumber(DEFAULT_CONTEXT_WINDOW)}-token window.`,
  );
  lines.push('');
  lines.push(`Last generated: ${new Date().toISOString().replace(/\.\d{3}Z$/, 'Z')}`);
  lines.push('');
  lines.push(
    `${scored.length} server(s) scored live, ${pending.length} pending. ` +
      'Lower is better: these tokens are spent on every request before the conversation starts.',
  );
  lines.push('');

  if (scored.length > 0) {
    const totalTokens = scored.reduce((sum, r) => sum + (r.score?.totalTokens ?? 0), 0);
    const totalTools = scored.reduce((sum, r) => sum + (r.score?.toolCount ?? 0), 0);

    lines.push('## Scored');
    lines.push('');
    lines.push('| # | Server | Tools | Tokens | Tokens/tool | Context @200k | Category |');
    lines.push('|---|---|---:|---:|---:|---:|---|');
    scored.forEach((row, index) => {
      const score = row.score;
      if (!score) {
        return;
      }
      lines.push(
        `| ${index + 1} ` +
          `| [${escapePipes(row.entry.name)}](${row.entry.repo}) ` +
          `| ${score.toolCount} ` +
          `| ${formatNumber(score.totalTokens)} ` +
          `| ${score.meanTokensPerTool} ` +
          `| ${formatPercent(score.contextShare)} ` +
          `| ${row.entry.category ?? 'other'} |`,
      );
    });
    lines.push('');
    lines.push(
      `Across the ${scored.length} scored servers: ${formatNumber(totalTools)} tools, ` +
        `${formatNumber(totalTokens)} tokens. Loading all of them at once would consume ` +
        `${formatPercent(totalTokens / DEFAULT_CONTEXT_WINDOW)} of a 200k context window before ` +
        'a single user message.',
    );
    lines.push('');
  }

  if (pending.length > 0) {
    lines.push('## Pending');
    lines.push('');
    lines.push(
      'These entries are structurally valid but their schema could not be fetched in the last run. ' +
        'No score is shown, because tooltax never publishes a number it did not measure.',
    );
    lines.push('');
    lines.push('| Server | Category | Why it is pending |');
    lines.push('|---|---|---|');
    for (const row of pending) {
      lines.push(
        `| [${escapePipes(row.entry.name)}](${row.entry.repo}) ` +
          `| ${row.entry.category ?? 'other'} ` +
          `| ${escapePipes(shorten(row.reason ?? 'unknown'))} |`,
      );
    }
    lines.push('');
  }

  lines.push('## Method');
  lines.push('');
  lines.push(
    'Each server is launched, asked for its tool list over the MCP protocol, and every tool ' +
      'definition is serialized to canonical JSON and tokenized. See `README.md` for the full ' +
      'methodology and its limits.',
  );
  lines.push('');

  return `${lines.join('\n')}\n`;
}

function escapePipes(text: string): string {
  return text.replace(/\|/g, '\\|');
}

function shorten(text: string, max = 120): string {
  const flat = text.replace(/\s+/g, ' ').trim();
  return flat.length <= max ? flat : `${flat.slice(0, max - 3)}...`;
}

export function formatNumber(value: number): string {
  return value.toLocaleString('en-US');
}

export function formatPercent(share: number): string {
  const percent = share * 100;
  if (percent > 0 && percent < 0.1) {
    return '<0.1%';
  }
  return `${percent.toFixed(1)}%`;
}
